# Use an official Node runtime as base image
FROM node:16-alpine

RUN apk add --no-cache make gcc g++ python3
# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json for optimal caching
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire app source
COPY . .

# Expose port
EXPOSE 30043

# Start the application
CMD ["npm", "start"]
